### ISSUE TITLE
Collecting metrics & Documentation

### ISSUE THREAD

**Issue by Zmitchell0811** [GeoffreyHecht/paprika#6]
I am getting a null pointer exception thrown when trying to collect metrics for an apk.
Here is what I get when the exception is thrown:
java.lang.NullPointerException
	at soot.JastAddJ.Program.initPaths(Program.java:350)
	at soot.SootResolver.<init>(SootResolver.java:89)
	at soot.Singletons.soot_SootResolver(Singletons.java:802)
	at soot.SootResolver.v(SootResolver.java:92)
	at soot.Scene.tryLoadClass(Scene.java:661)
	at soot.Scene.loadBasicClasses(Scene.java:1257)
	at soot.Scene.loadNecessaryClasses(Scene.java:1336)
	at paprika.analyzer.SootAnalyzer.init(SootAnalyzer.java:103)
	at paprika.Main.runAnalysis(Main.java:113)
	at paprika.Main.main(Main.java:80)

On a side note you may want to mention that the program looks for a folder named "android--1" in the path that is given by the user when using the "-a" flag

**Comment by GeoffreyHecht** [comment]
Hello, 
Indeed, the program looks for some android platforms that you should download  and points to with -a (you can see the address in the documentation : https://github.com/Sable/android-platforms ). 

It will probably solve your problem, if not please give me the list of arguments you are using :).

**Comment by Zmitchell0811** [comment]
Here are the lists of arguments I am using:

**Comment by Zmitchell0811** [comment]
java -Xmx2G -XX:+UseConcMarkSweepGC -jar Paprika.jar analyse -a /home/zachary -db /home/zachary/Database -n "Pokemon Go" -p "pokemon-go-0-91-2.apk" -c /home/zachary/Apk_CSV -k 70b129bae715afa70de2f783a05ac1240d3a2663041b7953f58532195e9cb953 -dev "Niantic, inc" -cat "Game" -nd "500000000" -d "2017-01-001 10:23:39.050315" -r 1.0 -s 94046337 -u UNSAFE /home/zachary/Apk/pokemon-go-0-91-2.apk

**Comment by Zmitchell0811** [comment]
java -jar Paprika.jar analyse -a /home/zachary -db /home/zachary/Database -n "Pokemon Go" -p "pokemon-go-0-91-2.apk" -c /home/zachary/Apk_CSV -k 70b129bae715afa70de2f783a05ac1240d3a2663041b7953f58532195e9cb953 -dev "Niantic, inc" -cat "Game" -nd "500000000" -d "2017-01-001 10:23:39.050315" -r 1.0 -s 94046337 -u UNSAFE /home/zachary/Apk/pokemon-go-0-91-2.apk

**Comment by GeoffreyHecht** [comment]
Sorry for the late reply.
I tested it on my side with the same apk and everything sounds to work well.
Please note that in your case the -p option will be : com.nianticlabs.pokemongo
Also you don't need -c in analyse mode (only in query). 
Also you need to download some android-platforms [from here](https://github.com/Sable/android-platforms) (this is likely the main reasons of the error) and provide a link to the folder with -a.
So your command line will look like :+1: 
`java -Xmx2G -XX:+UseConcMarkSweepGC -jar  Paprika.jar analyse -a /home/zachary/android platforms -k 70b129bae715afa70de2f783a05ac1240d3a2663041b7953f58532195e9cb953 -db "/home/zachary/Database" -n "Pokemon Go" -p "com.nianticlabs.pokemongo" -dev "Niantic, inc" -cat "Game" -nd "500000000" -d "2017-01-001 10:23:39.050315" -r 1.0 -s 94046337 -u "unsafe mode" /home/zachary/Apk/pokemon-go-0-91-2.apk`

I hope it will help you.

**Comment by Zmitchell0811** [comment]
Hi now I am getting a new error. For some reason paprika is giving me an error. Here is what it is.
java -Xmx2G -XX:+UseConcMarkSweepGC -jar Paprika.jar analyse -a /home/zachary/android platforms -k 70b129bae715afa70de2f783a05ac1240d3a2663041b7953f58532195e9cb953 -db "/home/zachary/Database" -n "Pokemon Go" -p "com.nianticlabs.pokemongo" -dev "Niantic, inc" -cat "Game" -nd "500000000" -d "2017-01-001 10:23:39.050315" -r 1.0 -s 94046337 -u "unsafe mode" /home/zachary/Apk/pokemon-go-0-91-2.apk
usage: paprika analyse [-h] -a ANDROIDJARS -db DATABASE -n NAME -p PACKAGE -k KEY -dev DEVELOPER -cat CATEGORY -nd NBDOWNLOAD -d DATE -r RATING [-pr PRICE] -s SIZE [-u UNSAFE] [-vc VERSIONCODE]
               [-vn VERSIONNAME] [-tsdk TARGETSDKVERSION] [-sdk SDKVERSION] [-omp ONLYMAINPACKAGE] apk
paprika: error: unrecognized arguments: '/home/zachary/Apk/pokemon-go-0-91-2.apk'

**Comment by k0pernicus** [comment]
Hi @Zmitchell0811, I think your error is the path given to the option `--androidJars`.
Indeed, the Java library will not parse correctly the input `/home/zachary/android platforms` because there is a space character between `android` and `platforms` - so the library will interpret `platforms` as the the Paprika APK (because `platforms` does not contains any recognizable form of option like `-` or `--`).
So, this may work (actually, it works on my machine):
```
java -Xmx2G -XX:+UseConcMarkSweepGC -jar Paprika.jar analyse -a "/home/zachary/android platforms" -k 70b129bae715afa70de2f783a05ac1240d3a2663041b7953f58532195e9cb953 -db "/home/zachary/Database" -n "Pokemon Go" -p "com.nianticlabs.pokemongo" -dev "Niantic, inc" -cat "Game" -nd "500000000" -d "2017-01-001 10:23:39.050315" -r 1.0 -s 94046337 -u "unsafe mode" /home/zachary/Apk/pokemon-go-0-91-2.apk
```

**Comment by brunomateus** [comment]
```
java -Xmx2G -XX:+UseConcMarkSweepGC -jar  Paprika.jar analyse -a "/tmp/android-platforms" -db "/tmp/neo4j" -n "basecamp" -p "com.basecamp.bc3" -k 033d2482aa3908789ff7b44e4d43d56dbc449cf803701476c117790afac6d6ad -dev mydev -cat mycat -nd 100 -d "2017-01-001 10:23:39.050315" -r 1.0 -s 1024 -u "unsafe mode" /tmp/basecamp.apk
```

**Comment by k0pernicus** [comment]
Hello @brunomateus 

Are you using Java 1.9 ?
@GeoffreyHecht and me tested the app and it seems some problems appear with Java 1.9 and the `Soot` library...

For example, using the 1.8.0_161 JDK:
```
$ /Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/bin/java -Xmx2G -XX:+UseConcMarkSweepGC -jar  Paprika.jar analyse -a "/tmp/android-platforms" -db "/tmp/neo4j" -n "myapp" -p "com.nianticlabs.pokemongo" -k sha256oftheAPK -dev mydev -cat mycat -nd 100 -d "2017-01-001 10:23:39.050315" -r 1.0 -s 1024 -u "unsafe mode" ~/Code/paprika/APK/pokemongo.apk
Collecting metrics
^C%
```
... using the 1.9.0.4 JDK:
```
$ /Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home/bin/java -Xmx2G -XX:+UseConcMarkSweepGC -jar  Paprika.jar analyse -a "/tmp/android-platforms" -db "/tmp/neo4j" -n "myapp" -p "com.nianticlabs.pokemongo" -k sha256oftheAPK -dev mydev -cat mycat -nd 100 -d "2017-01-001 10:23:39.050315" -r 1.0 -s 1024 -u "unsafe mode" ~/Code/paprika/APK/pokemongo.apk
Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Collecting metrics
java.lang.NullPointerException
	at soot.JastAddJ.Program.initPaths(Program.java:350)
	at soot.SootResolver.<init>(SootResolver.java:89)
	at soot.Singletons.soot_SootResolver(Singletons.java:802)
	at soot.SootResolver.v(SootResolver.java:92)
	at soot.Scene.tryLoadClass(Scene.java:661)
	at soot.Scene.loadBasicClasses(Scene.java:1257)
	at soot.Scene.loadNecessaryClasses(Scene.java:1336)
	at paprika.analyzer.SootAnalyzer.init(SootAnalyzer.java:97)
	at paprika.Main.runAnalysis(Main.java:113)
	at paprika.Main.main(Main.java:80)
```

**Comment by GeoffreyHecht** [comment]
So I confirm the error seems to appear only with Java 9 (and I don't think there is much we can do in Paprika to fix this).
But it work well on the bandcamp apk with java7 or 8.

(Thanks @k0pernicus for the help with this :) )

**Comment by k0pernicus** [comment]
@GeoffreyHecht Actually, it seems that `Soot` have some strong problems with Java 1.8, regarding [this issue](https://github.com/Sable/soot/issues/874), or [this other issue](https://github.com/Sable/soot/issues/896)...
So, maybe 1.7.X JDK may be better for analysis.

**Comment by GeoffreyHecht** [comment]
So far, I didn't have any exception with 8 but 7 is probably the safest choice then (until Paprika is updated with the Soot-j9 branch in an unlikely future).

**Comment by brunomateus** [comment]
@k0pernicus and @GeoffreyHecht , yes, I am using Java 1.9. I'll definitely try with Java 1.8 or 1.7. The weird thing is, I could analyze the apk using soot jar file (without paprika) even using Java 1.9. It's worked.

Thank you guys for the quickly response.

**Comment by k0pernicus** [comment]
Btw, is it working now @Zmitchell0811 ?

**Comment by Zmitchell0811** [comment]
I changed over to java 8 but it is still not working, I am now getting a new error:

**Comment by Zmitchell0811** [comment]
at soot.Scene.getAndroidAPIVersion(Scene.java:320)
	at soot.Scene.getAndroidJarPath(Scene.java:302)
	at soot.Scene.defaultClassPath(Scene.java:499)
	at soot.Scene.getSootClassPath(Scene.java:230)
	at soot.SootResolver.<init>(SootResolver.java:82)
	at soot.Singletons.soot_SootResolver(Singletons.java:802)
	at soot.SootResolver.v(SootResolver.java:92)
	at soot.Scene.tryLoadClass(Scene.java:661)
	at soot.Scene.loadBasicClasses(Scene.java:1257)
	at soot.Scene.loadNecessaryClasses(Scene.java:1336)
	at paprika.analyzer.SootAnalyzer.init(SootAnalyzer.java:103)
	at paprika.Main.runAnalysis(Main.java:113)
	at paprika.Main.main(Main.java:80)

**Comment by Zmitchell0811** [comment]
They removed the binaries for java 7 and I don't have access to an oracle support account so I do not have access to it.

**Comment by Zmitchell0811** [comment]
What android platforms are you using so I can test whether or not this is the issue.

**Comment by k0pernicus** [comment]
Hello @Zmitchell0811,
What is your issue?
The Android platforms are given in the README, [here](https://github.com/Sable/android-platforms).
Please, do not close and open the same issue again.

**Comment by k0pernicus** [comment]
As this issue has been resolved (the documentation has been updated and the first issue has been resolved now), I propose to close this issue.
@Zmitchell0811 Please to open a new issue and explain *fully* what is your problem please.
@GeoffreyHecht Are you agree with me ?

**Comment by GeoffreyHecht** [comment]
@k0pernicus Ok :+1: 
@Zmitchell0811 I will close the current issue, hoping that with the usage of the platform provided in the readme will solve your current problem. If you still encounter new errors, can you please open a new issue with the template provided by @k0pernicus [here](https://github.com/GeoffreyHecht/paprika/blob/master/ISSUE_TEMPLATE.md)?
 
Thank you !

**Comment by k0pernicus** [comment]
Actually, you just have to create a new issue [here](https://github.com/GeoffreyHecht/paprika/issues/new) ;-)

**Comment by Kritika1298** [comment]
Hi @GeoffreyHecht 
I am using Windows 10 and facing this issue. Please help me to rectify the error

![paprika_Error](https://user-images.githubusercontent.com/32808875/65232681-2e47b100-daef-11e9-9a3f-41ec165725ad.PNG)

**Comment by Kritika1298** [comment]
Hello, @GeoffreyHecht , I am using Java 1.7 in Windows 10 to operate Paprika but I am not successful and getting the following error. Please rectify it asap.


![paprika_Error](https://user-images.githubusercontent.com/32808875/65235842-04918880-daf5-11e9-8166-66b2c8798aca.PNG)
